import { LeaderEnum, PlacementTier, Stores, StoresEnum, TournamentType } from "./tournament.enum";

export const TournamentsData = [
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1641069995000, rounds: [] },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1641069995000, rounds: [] },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.RAID_N_TRADE, tournamentType: TournamentType.TreasureCup, players: 1024, placement: 47, date: 1672605995000, rounds: [] },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.RAID_N_TRADE, tournamentType: TournamentType.Regional, players: 1024, placement: 256, date: 1672605995000, rounds: [] },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.RAID_N_TRADE, tournamentType: TournamentType.Regional, players: 1024, placement: 256, date: 1672605995000, rounds: [] },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.RAID_N_TRADE, tournamentType: TournamentType.Regional, players: 1024, placement: 256, date: 1672605995000, rounds: [] },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.PECOCCITANIA, tournamentType: TournamentType.Regional, players: 256, placement: 128, date: 1672605995000, rounds: [], location: 'Toulouse' },
    { leader: LeaderEnum.YELLOW_KATAKURI, store: StoresEnum.OPE, tournamentType: TournamentType.Regional, players: 1024, placement: 512, date: 1672605995000, rounds: [], location: 'Liverpool' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.PLAYERS_SPOT, tournamentType: TournamentType.StoreTreasureCup, players: 32, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.PLAYERS_SPOT, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.PLAYERS_SPOT, tournamentType: TournamentType.LocalMedium, players: 16, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.POP_N_PLAY, tournamentType: TournamentType.LocalMedium, players: 8, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.WEATHERLIGHT, tournamentType: TournamentType.StoreTreasureCup, players: 32, placement: 8, date: 1672605995000, rounds: [], location: 'Évora' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.CONFLUX, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.YELLOW_KATAKURI, store: StoresEnum.CRITICAL_HIT, tournamentType: TournamentType.StoreTreasureCup, players: 32, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.YELLOW_KATAKURI, store: StoresEnum.VERSUS, tournamentType: TournamentType.StoreTreasureCup, players: 32, placement: 4, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.YELLOW_KATAKURI, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.YELLOW_KATAKURI, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.PURPLE_LUFFY, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.BLUE_NAMI, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RG_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RG_LAW, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.CRITICAL_HIT, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1672605995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.YELLOW_ENEL, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 8, date: 1704314795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.YELLOW_KATAKURI, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1704573995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1704919595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 8, date: 1707338795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1709757995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1710362795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1710967595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1711226795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalSmall, players: 6, placement: 1, date: 1711313195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1711831595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1712177195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalMedium, players: 16, placement: 1, date: 1712436395000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1712781995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1713041195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1713473195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalMedium, players: 16, placement: 1, date: 1713645995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1713991595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1714250795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.PECOCCITANIA, tournamentType: TournamentType.Regional, players: 1024, placement: 512, date: 1716065195000, rounds: [], location: 'Toulouse' },
    { leader: LeaderEnum.BY_ACE, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1717015595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.TAVERNA, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1718052395000, rounds: [], location: 'Curitiba' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.MERURU, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1718916395000, rounds: [], location: 'Curitiba' },
    { leader: LeaderEnum.GREEN_BONNEY, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1719780395000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.PLAYERS_SPOT, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1720298795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1720644395000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ACE, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1721249195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1722458795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LAW, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 8, date: 1722717995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalMedium, players: 16, placement: 1, date: 1728161195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1729802795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_SHANKS, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1734295595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_SHANKS, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1734900395000, rounds: [], location: 'Lisboa' },
    //2025
    { leader: LeaderEnum.RED_SHANKS, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 8, date: 1736369195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_SHANKS, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1736628395000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_SHANKS, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 8, date: 1737578795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_SHANKS, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1738183595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LUFFY, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1739393195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RU_MARCO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1740602795000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RU_MARCO, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1740861995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1741553195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.PTMERCH, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1742676395000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.OPE, tournamentType: TournamentType.RegionalSideEvent, players: 64, placement: 4, date: 1744490795000, rounds: [], location: 'Londres' },
    { leader: LeaderEnum.RP_LUFFY, store: StoresEnum.GG_LOUNGE, tournamentType: TournamentType.StoreChampionship, players: 32, placement: 4, date: 1745095595000, rounds: [], location: 'Viseu' },
    { leader: LeaderEnum.RP_LUFFY, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 8, date: 1745441195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RU_MARCO, store: StoresEnum.LOTUS_MARKET, tournamentType: TournamentType.LocalSmall, players: 8, placement: 2, date: 1745527595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1746391595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RP_LUFFY, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 8, date: 1746909995000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RU_MARCO, store: StoresEnum.MERCADIA, tournamentType: TournamentType.LocalMedium, players: 16, placement: 4, date: 1747169195000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.MERCADIA, tournamentType: TournamentType.LocalMedium, players: 16, placement: 1, date: 1749588395000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1749674795000, rounds: [], location: 'Lisboa' },
    {
        leader: LeaderEnum.RU_MARCO,
        store: StoresEnum.GAMERSWORLD,
        tournamentType: TournamentType.Regional,
        players: 256,
        placement: 84,
        date: 1749933995000,
        rounds: [
            { number: 1, opponent: LeaderEnum.GY_LAW, wonDice: false, won: true },
            { number: 3, opponent: LeaderEnum.UP_LUFFY, wonDice: false, won: true },
            { number: 4, opponent: LeaderEnum.UP_LUFFY, wonDice: false, won: true },
            { number: 2, opponent: LeaderEnum.RG_SMOKER, wonDice: false, won: false },
            { number: 5, opponent: LeaderEnum.RY_BETTY, wonDice: false, won: false },
            { number: 6, opponent: LeaderEnum.BLUE_BUGGY, wonDice: false, won: true },
            { number: 7, opponent: LeaderEnum.YELLOW_KALGARA, wonDice: false, won: false },
            { number: 8, opponent: LeaderEnum.GP_LUFFY, wonDice: false, won: false },
        ],
        location: 'Dublin'
    },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 4, date: 1750279595000, rounds: [], location: 'Lisboa' },
    { leader: LeaderEnum.RU_MARCO, store: StoresEnum.VERSUS, tournamentType: TournamentType.LocalBig, players: 20, placement: 1, date: 1750884395000, rounds: [], location: 'Lisboa' },
    {
        leader: LeaderEnum.RU_MARCO,
        store: StoresEnum.PECOCCITANIA,
        tournamentType: TournamentType.Regional,
        players: 1024,
        placement: 301,
        date: 1751143595000,
        rounds: [
            { number: 1, opponent: LeaderEnum.RY_BETTY, wonDice: false, won: true },
            { number: 2, opponent: LeaderEnum.RG_SMOKER, wonDice: false, won: true },
            { number: 3, opponent: LeaderEnum.UP_LUFFY, wonDice: false, won: false },
            { number: 4, opponent: LeaderEnum.BLUE_BUGGY, wonDice: false, won: false },
            { number: 5, opponent: LeaderEnum.UP_REIJU, wonDice: false, won: false },
            { number: 6, opponent: LeaderEnum.BLUE_NAMI, wonDice: false, won: true },
            { number: 7, opponent: LeaderEnum.PB_LUFFY, wonDice: false, won: true },
            { number: 8, opponent: LeaderEnum.BLACK_TEACH, wonDice: false, won: false },
        ],
        location: 'Toulouse'
    },
    { leader: LeaderEnum.RED_ZORO, store: StoresEnum.DUELOS_DE_HONRA, tournamentType: TournamentType.LocalSmall, players: 8, placement: 1, date: 1751834795000, rounds: [], location: 'Lisboa' },
    {
        leader: LeaderEnum.RED_ZORO,
        store: StoresEnum.PECOCCITANIA,
        tournamentType: TournamentType.Finals,
        players: 512,
        placement: 170,
        date: 1754167595000,
        rounds: [
            { number: 1, opponent: LeaderEnum.GY_LAW, wonDice: false, won: true },
            { number: 2, opponent: LeaderEnum.BLUE_BUGGY, wonDice: false, won: false },
            { number: 3, opponent: LeaderEnum.UP_LUFFY, wonDice: false, won: false },
            { number: 4, opponent: LeaderEnum.UP_LUFFY, wonDice: false, won: true },
            { number: 5, opponent: LeaderEnum.RY_BETTY, wonDice: false, won: true },
            { number: 6, opponent: LeaderEnum.BLUE_BUGGY, wonDice: false, won: false },
            { number: 7, opponent: LeaderEnum.PB_LUFFY, wonDice: false, won: false },
            { number: 8, opponent: LeaderEnum.RED_ZORO, wonDice: false, won: true },
        ],
        location: 'Paris'
    },
    //OP12
    {
        leader: LeaderEnum.RED_SHANKS,
        store: StoresEnum.VERSUS,
        tournamentType: TournamentType.LocalSmall,
        players: 8,
        placement: 2,
        date: 1755722795000,
        rounds: [
            { number: 1, opponent: LeaderEnum.UP_REIJU, wonDice: true, won: true },
            { number: 2, opponent: LeaderEnum.RED_RAYLEIGH, wonDice: true, won: true },
            { number: 3, opponent: LeaderEnum.UP_REIJU, wonDice: false, won: false },
        ],
        location: 'Lisboa'
    },
    {
        leader: LeaderEnum.RED_RAYLEIGH,
        store: StoresEnum.VERSUS,
        tournamentType: TournamentType.LocalBig,
        players: 20,
        placement: 2,
        date: 1755981995000,
        rounds: [
            { number: 1, opponent: LeaderEnum.UP_SANJI, wonDice: true, won: true },
            { number: 2, opponent: LeaderEnum.PB_LUFFY, wonDice: true, won: true },
            { number: 3, opponent: LeaderEnum.RED_ZORO, wonDice: true, won: true },
            { number: 4, opponent: LeaderEnum.PURPLE_LUFFY, wonDice: false, won: false },
        ],
        location: 'Lisboa'
    },
    {
        leader: LeaderEnum.RED_RAYLEIGH,
        store: StoresEnum.VERSUS,
        tournamentType: TournamentType.LocalBig,
        players: 14,
        placement: 4,
        date: 1756260262000,
        rounds: [
            { number: 1, opponent: LeaderEnum.BLACK_TEACH, wonDice: false, won: false },
            { number: 2, opponent: LeaderEnum.BLUE_KUZAN, wonDice: false, won: true },
            { number: 3, opponent: LeaderEnum.UP_REIJU, wonDice: false, won: true },
            { number: 4, opponent: LeaderEnum.PB_LUFFY, wonDice: false, won: false },
        ],
        location: 'Lisboa'
    },
    {
        leader: LeaderEnum.RED_SHANKS,
        store: StoresEnum.LOTUS_MARKET,
        tournamentType: TournamentType.LocalSmall,
        players: 8,
        placement: 1,
        date: 1756413995000,
        rounds: [
            { number: 1, opponent: LeaderEnum.PURPLE_LUFFY, wonDice: false, won: true },
            { number: 2, opponent: LeaderEnum.UP_REIJU, wonDice: true, won: true },
            { number: 3, opponent: LeaderEnum.RB_KOBY, wonDice: false, won: true },
        ],
        location: 'Lisboa'
    },
]