export const eventsNames = [
    '',
    'But Ace Here Said You Deserved It!!',
    'Arabesque Brick Fist',
    'Artificial Devil Fruit SMILE',
    'Meteor Fist',
    'Gum-Gum Gatling Gun',
    'Windmill Village',
    'Gum-Gum Elephant Gun',
    'Gum-Gum Snake Shot',
    'I Know You\'re Strong... So I\'ll Go All Out from the Very Start!!!',
    'If I Bowed Down to Power, What\'s the Point in Living?',
    'Phoenix Pyreapple',
    'Brilliant Punk',
    'Guess We\'ll Have Another Scrap. You Can Only Risk Death While You\'re Still Alive!!',
    'Divine Departure',
    'Go All the Way to the Top!!',
    'Oro Jackson',
    'The Five Elders Are at Your Service!!!',
    'The World\'s Equilibrium Cannot Be Maintained Forever',
    'Never Existed... in the First Place...',
    'The Empty Throne',
    'Paper Art Afterimage',
    'The One Who Is the Most Free Is the Pirate King!!!',
    'Gum-Gum Dawn Stamp',
    'Eleclaw',
    'Shark Brick Fist',
    'Ice Time',
    'I Heard the Sound...of a Lady\'s Teardrops Falling',
    'Flame Dragon Torch',
    'Stealth Black',
    'Chambres',
    'Time for the Counterattack',
    'I Have a Plan to Take Down One of the Four Emperors!!',
    'Strive to Surpass me, Roronoa Zoro!!!',
    'For Fun',
    'I Never Bother to Remember the Faces of Trash',
    'Coffin Boat',
    'Don\'t Worry!! I\'m Here!!',
    'Ocean Current Shoulder Throw',
    'Please Take Me with You!! I Can Be of Great Help to You!!',
    'Ever White',
    'Penta-Chromatic String',
    'Bullet String',
    'Ground Death',
    'Hurry Up and Make Me the Pirate King!',
    'Crescent Cutlass',
    'Disappointed?',
    'Salamander',
    'Brick Bat',
    'You\'ll Frighten Me... ♡',
    'Raw Heat Strike',
    'Kizaru!! Compared to Two Years Ago We\'re a Hundred Times Stronger Now!!',
    'Iai Death Lion Song',
    'But If We Ever See Each Other Again... Will You Call Me Your Shipmate?!!',
    'There You Are, Sore Loser!',
    'Insolent Fool!! Stand Down!!',
    'Thanks for the Treat. ♡',
    'I Knew You People Were Behind This.',
]