export const nameOptions = [
    'Adio',
    'Alvida',
    'Apis',
    'Arabesque Brick Fist',
    'Arlong',
    'Artificial Devil Fruit SMILE',
    'Ashura Doji',
    'Atmos',
    'Baby 5',
    'Babanuki',
    'Bananagator',
    'Baratie',
    'Bartholomew Kuma',
    'Bartolomeo',
    'Bastille',
    'Basil Hawkins',
    'BE-BENG!!',
    'Bellamy',
    'Bell-mère',
    'Belo Betty',
    'Bepo',
    'Boeuf Burst',
    'Boa Hancock',
    'Bobbin the Disposer',
    'Boodle',
    'Borsalino',
    'Black Maria',
    'Blamenco',
    'Blenheim',
    'Blueno',
    'Blugori',
    'Brannew',
    'Brook',
    'Brochette Blow',
    'Buggy',
    'Byrnndi World',
    'Buchi',
    'Buffalo',
    'Cabaji',
    'Caesar Clown',
    'Camie',
    'Capone "Gang" Bege',
    'Captains Assembled',
    'Caribou',
    'Carme',
    'Carmel',
    'Carmen',
    'Carne',
    'Carrot',
    'Cavendish',
    'Chaka',
    'Charlotte Amande',
    'Charlotte Bavarois',
    'Charlotte Chiffon',
    'Charlotte Cracker',
    'Charlotte Galette',
    'Charlotte Katakuri',
    'Charlotte Linlin',
    'Charlotte Moscato',
    'Charlotte Opera',
    'Charlotte Oven',
    'Charlotte Perospero',
    'Charlotte Praline',
    'Charlotte Pudding',
    'Charlotte Smoothie',
    'Chew',
    'Chimney & Gonbe',
    'Chinjao',
    'Concasser',
    'Corgy',
    'Crescent Cutlass',
    'Crocodile',
    'Curiel',
    'Curly Dadan',
    'Daddy Masterson',
    'Daifugo',
    'DEATH WINK',
    'Dellinger',
    'Demon Face',
    'Desert Spada',
    'Diable Jambe Venaison Shoot',
    'Diamante',
    'Doberman',
    'Dobon',
    'Dogura',
    'Domino',
    'Donquixote Doflamingo',
    'Donquixote Rosinante',
    'Douglas Bullet',
    'Dracule Mihawk',
    'Edward Newgate',
    'Elephant\'s Marchoo',
    'Emporio Ivankov',
    'Eric',
    'Eustass "Captain" Kid',
    'Fossa',
    'Fullbody',
    'Fukurokuju',
    'Fukurou',
    'Franky',
    'Gecko Moria',
    'Genzo',
    'Gin',
    'Giolla',
    'Gordon',
    'Green Star Rafflesia',
    'Gum-Gum Fire-Fist Pistol Red Hawk',
    'Gum-Gum Rain',
    'Gyats',
    'Hack',
    'Hair Removal Fist',
    'Hajrudin',
    'Hanger',
    'Hannyabal',
    'Haruta',
    'Hatchan',
    'Helmeppo',
    'Hera',
    'Hina',
    'Hitokiri Kamazo',
    'Holedem',
    'Hydra',
    'Hyogoro',
    'I Love You!!',
    'I Will Make Whitebeard the King of the Pirates',
    'Ice Age',
    'Ice Block Pheasant Peck',
    'Ice Oni',
    'Iceburg',
    'Ideo',
    'Igaram',
    'Impel Down',
    'Impel Down All Stars',
    'In Two Years!! At the Sabaody Archipelago!!',
    'Inazuma',
    'Inuarashi',
    'Ipponmatsu',
    'Issho',
    'Isuka',
    'Izo',
    'Jabra',
    'Jack',
    'Jaguar D. Saul',
    'Jango',
    'Jean Bart',
    'Jerry',
    'Jewelry Bonney',
    'Jinbe',
    'Jozu',
    'Judgment of Hell',
    'Kaido',
    'Kaku',
    'Kalgara',
    'Kalifa',
    'Kanjuro',
    'Karasu',
    'Karoo',
    'Kawamatsu',
    'Kaya',
    'Kin\'emon',
    'King',
    'Kingbaum',
    'Kingdew',
    'Kiwi & Mozu',
    'Koala',
    'Koby',
    'Kokoro',
    'Komachiyo',
    'Komille',
    'Komurasaki',
    'Kouzuki Hiyori',
    'Kouzuki Momonosuke',
    'Kouzuki Oden',
    'Kouzuki Toki',
    'Koza',
    'Krieg',
    'Kumadori',
    'Kung Fu Jugon',
    'Kuro',
    'Kuroobi',
    'Kurozumi Higurashi',
    'Kurozumi Orochi',
    'Kurozumi Semimaru',
    'Kyoshirou',
    'Kyros',
    'Kuzan',
    'Land of Wano',
    'Lao G',
    'Leo',
    'Lindbergh',
    'Lim',
    'Little Oars Jr.',
    'Little Sadi',
    'Luffy Is the Man Who Will Be King of the Pirates!!!',
    'Machvise',
    'Magellan',
    'Magura',
    'Makino',
    'Marco',
    'Marshall D. Teach',
    'Masked Deuce',
    'Merry',
    'Meteor Volcano',
    'Minokoala',
    'Minorhinoceros',
    'Minotaur',
    'Minozebra',
    'Miss All Sunday',
    'Miss Doublefinger (Zala)',
    'Miss Goldenweek (Marianne)',
    'Miss Merry Christmas (Drophy)',
    'Miss Valentine (Mikita)',
    'Mizerka',
    'Moby Dick',
    'Mocha',
    'Momoo',
    'Mohji',
    'Mohji & Cabaji',
    'Monkey D. Dragon',
    'Monkey D. Garp',
    'Monkey D. Luffy',
    'Monet',
    'Morley',
    'Ms. All Sunday',
    'Mr. 1 (Daz Bonez)',
    'Mr. 2 Bon Kurei (Bentham)',
    'Mr. 3 (Galdino)',
    'Mr. 4 (Babe)',
    'Mr. 5 (Gem)',
    'Mr. 13 & Miss Friday',
    'Nami',
    'Napoleon',
    'Nefeltari Cobra',
    'Nefeltari Vivi',
    'Nekomamushi',
    'Nero',
    'New Kama Land',
    'Nico Robin',
    'Officer Agents',
    'Oimo & Kashii',
    'Okiku',
    'Olin',
    'Onigumo',
    'Orlumbus',
    'Otama',
    'Otsuru',
    'Overheat',
    'Page One',
    'Pacifista',
    'Paradise Totsuka',
    'Paradise Waterfall',
    'Patty',
    'Paulie',
    'Pearl',
    'Peepley Lulu',
    'Penguim',
    'Pell',
    'Perona',
    'Poker',
    'Portgas D. Ace',
    'Pound',
    'Punk Gibson',
    'Queen',
    'Rabiyan',
    'Radical Beam!!',
    'Raizo',
    'Rakuyo',
    'Randolph',
    'Rebecca',
    'Rob Lucci',
    'Rokki',
    'Roronoa Zoro',
    'Round Table',
    'Sabo',
    'Sai',
    'Sakazuki',
    'Saldeath',
    'Sanji',
    'Sasaki',
    'Scratchmen Apoo',
    'Seaquake',
    'Sengoku',
    'Senor Pink',
    'Sentomaru',
    'Seto',
    'Shachi',
    'Sham',
    'Shanks',
    'Shehirahoshi',
    'Shiki',
    'Shinobu',
    'Shirley',
    'Sheep\'s Horn',
    'Shirahoshi',
    'Shinobu',
    'Shiryu',
    'Shishilian',
    'Smiley',
    'Smoker',
    'Slam Gibson',
    'Sogeking',
    'Solitaire',
    'Spandam',
    'Speed',
    'Speed Jil',
    'Sphinx',
    'Squard',
    'Strawberry',
    'Streusen',
    'Stussy',
    'Sugar',
    'Suleiman',
    'Super Spot-Billed Duck Troops',
    'Tashigi',
    'Thatch',
    'The "Extinguishes All Sound Created by Your Influence" Technique',
    'Three Sword Style Oni Giri',
    'Thunder Bagua',
    'Tilestone',
    'Toko',
    'Tom',
    'Tonoyasu',
    'Tony Tony Chopper',
    'Trafalgar Lammy',
    'Trafalgar Law',
    'Trebol',
    'Tsuru',
    'Ulti',
    'Ulti-Mortar',
    'Urashima',
    'Ursa Shock',
    'Usopp',
    'Usopp\'s Pirate Crew',
    'Uta',
    'Vinsmoke Reiju',
    'Vinsmoke Sora',
    'Viola',
    'Vista',
    'Venom Road',
    'Vergo',
    'Wanda',
    'Wanze',
    'We\'ll Ring the Bell Waiting for You!!',
    'Whitebeard Pirates',
    'Whitey Bay',
    'Who\'s Who',
    'Wire',
    'Wyper',
    'X Drake',
    'Yamakaji',
    'Yamato',
    'Yasakani Sacred Jewel',
    'Yasopp',
    'Yokozuna',
    'Yosaku & Johnny',
    'You Can Be My Samurai!!',
    'You May Be a Fool...but I Still Love You',
    'Zambai',
    'Zeff',
    'Zephyr',
    'Zephyr(Navy)',
    'Zoro-Juurou',
];
