export const nameOptions = [
    '',
    'Absalom',
    'Adio',
    'Ain',
    'Aisa',
    'Aladine',
    'Alber',
    'All-Hunt Grount',
    'Ann',
    'Avalo Pizarro',
    'Alvida',
    'Amazon',
    'Apis',
    'Aphelandra',
    'Arabesque Brick Fist',
    'Aramaki',
    'Arlong',
    'Army Wolves',
    'Artificial Devil Fruit SMILE',
    'Ashura Doji',
    'Atlas',
    'Atmos',
    'Baby 5',
    'Babanuki',
    'Baccarat',
    'Bananagator',
    'Baratie',
    'Baron Omatsuri',
    'Baron Tamago',
    'Baroque Works',
    'Bartholomew Kuma',
    'Bartolomeo',
    'Baskerville',
    'Bastille',
    'Basil Hawkins',
    'BB',
    'BE-BENG!!',
    'Bear King',
    'Bellamy',
    'Bell-mère',
    'Belo Betty',
    'Benn Beckman',
    'Bepo',
    'Berry Good',
    'Bian',
    'Big Pan',
    'Bingou',
    'Bins',
    'Bird Neptunian',
    'Biscuit Warrior',
    'Bluejam',
    'Boeuf Burst',
    'Boa Hancock',
    'Boa Marigold',
    'Boa Sandersonia',
    'Bobbin the Disposer',
    'Bogard',
    'Bonk Punch',
    'Boodle',
    'Borsalino',
    'Black Maria',
    'Blamenco',
    'Blenheim',
    'Blue Gilly',
    'Blueno',
    'Blugori',
    'Braham',
    'Brannew',
    'Briscola',
    'Brook',
    'Brochette Blow',
    'Buckin',
    'Buena Festa',
    'Buggy',
    'Bunny Joe',
    'Byrnndi World',
    'Buchi',
    'Buffalo',
    'Building Snake',
    'Bulge-Eyed Neptunian',
    'Cabaji',
    'Caesar Clown',
    'Ceaser Soldier',
    'Camie',
    'Capone "Gang" Bege',
    'Capote',
    'Captain John',
    'Captain McKinley',
    'Captains Assembled',
    'Caribou',
    'Carina',
    'Carme',
    'Carmel',
    'Carmen',
    'Carne',
    'Carrot',
    'Catarina Devon',
    'Cavendish',
    'Cerberus',
    'Chadros Higelyges (Brownbeard)',
    'Chaka',
    'Charlotte Amande',
    'Charlotte Anana',
    'Charlotte Angel',
    'Charlotte Bavarois',
    'Charlotte Brulee',
    'Charlotte Chiffon',
    'Charlotte Compote',
    'Charlotte Cracker',
    'Charlotte Custard',
    'Charlotte Daifuku',
    'Charlotte Flampe',
    'Charlotte Galette',
    'Charlotte Katakuri',
    'Charlotte Linlin',
    'Charlotte Lola',
    'Charlotte Mont-d\'or',
    'Charlotte Moscato',
    'Charlotte Opera',
    'Charlotte Oven',
    'Charlotte Perospero',
    'Charlotte Poire',
    'Charlotte Praline',
    'Charlotte Pudding',
    'Charlotte Smoothie',
    'Chess',
    'ChessMarimo',
    'Chew',
    'Chopa-Emon',
    'Chopperman',
    'Chimney & Gonbe',
    'Chinjao',
    'Clone Soldier',
    'Concasser',
    'Concelot',
    'Conis',
    'Corgy',
    'Coribou',
    'Cosette',
    'Count Battler',
    'Count Niwatori',
    'Crescent Cutlass',
    'Crocodile',
    'Crocus',
    'Cross Fire',
    'Cub',
    'Curiel',
    'Curly Dadan',
    'Daddy Masterson',
    'Daifugo',
    'Dalmatian',
    'Dalton',
    'Daruma',
    'DEATH WINK',
    'Decuplets',
    'Dellinger',
    'Demon Face',
    'Denjiro',
    'Desert Spada',
    'Diable Jambe Venaison Shoot',
    'Diamante',
    'Dice',
    'Divine Departure',
    'Doberman',
    'Doc Q',
    'Dobon',
    'Dogura',
    'Dogura & Magura',
    'Doll',
    'Doma',
    'Domino',
    'Don Accino',
    'Donquixote Doflamingo',
    'Donquixote Rosinante',
    'Dosun',
    'Douglas Bullet',
    'Dr. Hiruluk',
    'Dr. Hogback',
    'Dr. Indigo',
    'Dr. Kureha',
    'Dracule Mihawk',
    'Dragon Number Thirteen',
    'Duval',
    'Edison',
    'Edward Newgate',
    'Edward Weevil',
    'Eldoraggo',
    'Elephant\'s Marchoo',
    'Elizabello II',
    'Emporio Ivankov',
    'Enel',
    'Eric',
    'Eustass "Captain" Kid',
    'Fake Straw Hat Crew',
    'Fiery Doll',
    'Fighting Fish',
    'Fire Fist',
    'Fisher Tiger',
    'Flame Emperror',
    'Fortricks',
    'Fossa',
    'Foxy',
    'Fullbody',
    'Fukaboshi',
    'Fukurokuju',
    'Fukurou',
    'Fuza',
    'Fra-Nosuke',
    'Franky',
    'Funkfreed',
    'Gaimon',
    'Gan Fall',
    'Gasparde',
    'Gastino',
    'Gecko Moria',
    'Gedatsu',
    'Genbo',
    'Genzo',
    'Gild Tesoro',
    'Gin',
    'Gina',
    'Ginrummy',
    'Giolla',
    'Gion',
    'Giovanni',
    'Gismonda',
    'Gladius',
    'Gloriosa (Grandma Nyon)',
    'Gol D. Roger',
    'Gordon',
    'Gotti',
    'Grandpa Ryu',
    'Green Star Rafflesia',
    'Guernica',
    'Gum-Gum Fire-Fist Pistol Red Hawk',
    'Gum-Gum Rain',
    'Gyats',
    'Gyro',
    'Haccha',
    'Hack',
    'Hair Removal Fist',
    'Hajrudin',
    'Hakuba',
    'Hamburg',
    'Hamlet',
    'Hammond',
    'Hanger',
    'Hannyabal',
    'Haruta',
    'Hatchan',
    'Hattori',
    'Heat',
    'Heat & Wire',
    'Helmeppo',
    'Hera',
    'Hibari',
    'Hiking Bear',
    'Hildon',
    'Hina',
    'Hitokiri Kamazo',
    'Hody Jones',
    'Holedem',
    'Holly',
    'Hone-Kichi',
    'Hongo',
    'Hotori',
    'Howling Gab',
    'Hydra',
    'Hyogoro',
    'Hyouzou',
    'I Love You!!',
    'I Will Make Whitebeard the King of the Pirates',
    'Ice Age',
    'Ice Block Pheasant Peck',
    'Ice Oni',
    'Iceburg',
    'Ideo',
    'Igaram',
    'Ikaros Muhni',
    'Impel Down',
    'Impel Down All Stars',
    'In Two Years!! At the Sabaody Archipelago!!',
    'Inazuma',
    'Inuarashi',
    'Inuppe',
    'Ipponmatsu',
    'Ishilly',
    'Issho',
    'Isuka',
    'Itomimizu',
    'Izo',
    'Jabra',
    'Jack',
    'Jaguar D. Saul',
    'Jango',
    'Jean Bart',
    'Jerry',
    'Jesus Burgess',
    'Jewelry Bonney',
    'Jigoro of the Wind',
    'Jinbe',
    'John Giant',
    'Jonathan',
    'Joseph',
    'Jozu',
    'Judgment of Hell',
    'Kaido',
    'Kaido & Linlin',
    'Kaku',
    'Kalgara',
    'Kalifa',
    'Kamakiri',
    'Kanjuro',
    'Karasu',
    'Karoo',
    'Kawamatsu',
    'Kaya',
    'Kid & Killer',
    'Kikunojo',
    'Killer',
    'Kin\'emon',
    'King',
    'Kingbaum',
    'Kingdew',
    'Kiwi & Mozu',
    'Klabautermann',
    'Koala',
    'Koby',
    'Kokoro',
    'Komachiyo',
    'Komei',
    'Komille',
    'Komurasaki',
    'Kotori',
    'Koushirou',
    'Kouzuki Hiyori',
    'Kouzuki Momonosuke',
    'Kouzuki Oden',
    'Kouzuki Toki',
    'Koza',
    'Krieg',
    'Kujyaku',
    'Kumacy',
    'Kumadori',
    'Kung Fu Jugon',
    'Kuro',
    'Kuromarimo',
    'Kuroobi',
    'Kurozumi Higurashi',
    'Kurozumi Orochi',
    'Kurozumi Semimaru',
    'Kuween',
    'Kuzan',
    'Kyoshirou',
    'Kyros',
    'Laboon',
    'Laffitte',
    'Land of Wano',
    'Lapins',
    'Lao G',
    'Leo',
    'Lieutenant Spacey',
    'Lillith',
    'Lily Carnation',
    'Lim',
    'Limejuice',
    'Lindbergh',
    'Little Oars Jr.',
    'Little Sadi',
    'Lola',
    'Long-Jaw Neptunian',
    'Lord of the Coast',
    'Lucky Roux',
    'Lucy',
    'Luffy Is the Man Who Will Be King of the Pirates!!!',
    'Machvise',
    'Mad Treasure',
    'Magellan',
    'Magura',
    'Maha',
    'Makino',
    'Mamboshi',
    'Mansherry',
    'Marco',
    'Marguerite',
    'Maria Onion Bear',
    'Marshall D. Teach',
    'Masked Deuce',
    'Maynard',
    'Megalo',
    'Merry',
    'Meteor Volcano',
    'Milky',
    'Minochiuaua',
    'Minokoala',
    'Minorhinoceros',
    'Minotaur',
    'Minozebra',
    'Miss All Sunday',
    'Miss Doublefinger (Zala)',
    'Miss Goldenweek (Marianne)',
    'Miss Merry Christmas (Drophy)',
    'Miss Monday',
    'Miss Sarahebi',
    'Miss Valentine (Mikita)',
    'Miss Wednesday',
    'Mizerka',
    'Miyagi',
    'Moby Dick',
    'Mocha',
    'Moda',
    'Momoo',
    'Monster',
    'Moocy',
    'Mohji',
    'Mohji & Cabaji',
    'Monda',
    'Monet',
    'Monkey D. Dragon',
    'Monkey D. Garp',
    'Monkey D. Luffy',
    'Mont Blanc Cricket',
    'Mont blanc Noland',
    'Morgan',
    'Morgans',
    'Morley',
    'Mozambia',
    'Ms. All Sunday',
    'Mr. 1 (Daz Bonez)',
    'Mr. 2 Bon Kurei (Bentham)',
    'Mr. 3 (Galdino)',
    'Mr. 4 (Babe)',
    'Mr. 5 (Gem)',
    'Mr. 9',
    'Mr. 13 & Miss Friday',
    'Mr. Tanaka',
    'Musshuru',
    'Myskina Olga',
    'Nami',
    'Namule',
    'Napoleon',
    'Nefeltari Cobra',
    'Nefeltari Vivi',
    'Nekomamushi',
    'Neptune',
    'Nero',
    'New Kama Land',
    'Nico Olvia',
    'Nola',
    'Nico Robin',
    'Nitro',
    'O-Nami',
    'O-Robi',
    'Officer Agents',
    'Ohm',
    'Oimo & Kashii',
    'Okiku',
    'Olin',
    'One-Legged Toy Soldier',
    'Onigumo',
    'Orlumbus',
    'Otama',
    'Otohime',
    'Otsuru',
    'Out-of-the-Bag',
    'Outlook III',
    'Overheat',
    'Page One',
    'Pacifista',
    'Pagaya',
    'Pappag',
    'Paradise Totsuka',
    'Paradise Waterfall',
    'Patty',
    'Paulie',
    'Peachbeard',
    'Pearl',
    'Pedro',
    'Peepley Lulu',
    'Pekoms',
    'Pell',
    'Penguim',
    'Perona',
    'Pica',
    'Pickles',
    'Pierre',
    'Poker',
    'Porche',
    'Porchemy',
    'Portgas D. Ace',
    'Pound',
    'Prince Bellett',
    'Prince Grus',
    'Professor Clover',
    'Punk Gibson',
    'Pythagoras',
    'Queen',
    'Rabiyan',
    'Radical Beam!!',
    'Raise Max',
    'Raizo',
    'Raki',
    'Rakuyo',
    'Randolph',
    'Ratchet',
    'Rebecca',
    'Richie',
    'Riku Doldo III',
    'Ripper',
    'Rob Lucci',
    'Robson',
    'Rock',
    'Rockstar',
    'Roddy',
    'Rokki',
    'Roronoa Zoro',
    'Round Table',
    'Ryuboshi',
    'Ryuma',
    'S-Bear',
    'S-Hawk',
    'S-Shark',
    'S-Snake',
    'Sabo',
    'Saga',
    'Sai',
    'Saint Charlos',
    'Saint Homing',
    'Saint Mjosgard',
    'Saint Rosward',
    'Sakazuki',
    'Saldeath',
    'Salome',
    'San-Gorou',
    'Sanji',
    'Sanji & Pudding',
    'Sanjuan Wolf',
    'Sarfunkel',
    'Sarquiss',
    'Sasaki',
    'Satori',
    'Scaled Neptunian',
    'Scarlet',
    'Schneider',
    'Scotch',
    'Scratchmen Apoo',
    'Seaquake',
    'Sengoku',
    'Senor Pink',
    'Sentomaru',
    'Seto',
    'Shachi',
    'Shachi & Penguin',
    'Shaka',
    'Shakuyaku',
    'Sham',
    'Shanks',
    'Sheepshead',
    'Shehirahoshi',
    'Shiki',
    'Shinobu',
    'Shirley',
    'Sheep\'s Horn',
    'Shirahoshi',
    'Shinobu',
    'Shishilian',
    'Shiryu',
    'Shishilian',
    'Shu',
    'Shura',
    'Shuraiya',
    'Silvers Rayleigh',
    'Smiley',
    'Smoker',
    'Slam Gibson',
    'Sogeking',
    'Solitaire',
    'South Bird',
    'Spandam',
    'Spandine',
    'Speed',
    'Speed Jil',
    'Sphinx',
    'Squard',
    'Stainless',
    'Sterry',
    'Strawberry',
    'Streusen',
    'Striker',
    'Stronger',
    'Stussy',
    'Sugar',
    'Suleiman',
    'Super Spot-Billed Duck Troops',
    'Surume',
    'Sweetpea',
    'T Bone',
    'Taralan',
    'Tashigi',
    'Tenguyama Hitetsu',
    'Thatch',
    'The "Extinguishes All Sound Created by Your Influence" Technique',
    'Three Sword Style Oni Giri',
    'Thunder Bagua',
    'Tilestone',
    'Toh-Toh',
    'Tokikake',
    'Toko',
    'Tom',
    'Tonjit',
    'Tonoyasu',
    'Tony Tony Chopper',
    'Tooth Attack',
    'Topknot Neptunian',
    'Tot Musica',
    'Trafalgar Lammy',
    'Trafalgar Law',
    'Trebol',
    'Tristan',
    'Tsuru',
    'Twenty Doctors',
    'Ulti',
    'Ulti-Mortar',
    'Urashima',
    'Urouge',
    'Ursa Shock',
    'Uso-Hachi',
    'Usopp',
    'Usopp\'s Pirate Crew',
    'Uta',
    'Van Augur',
    'Vander Decken IX',
    'Vasco Shot',
    'Vega Force 01',
    'Vegapunk',
    'Venom Road',
    'Vergo',
    'Victoria Cindry',
    'Vinsmoke Ichiji',
    'Vinsmoke Judge',
    'Vinsmoke Niji',
    'Vinsmoke Reiju',
    'Vinsmoke Sanji',
    'Vinsmoke Sora',
    'Vinsmoke Yonji',
    'Viola',
    'Violet',
    'Viscount Hiyoko',
    'Vista',
    'Vito',
    'Wadatsumi',
    'Wanda',
    'Wanze',
    'Wapol',
    'We\'ll Ring the Bell Waiting for You!!',
    'Whitebeard Pirates',
    'Whitey Bay',
    'Who\'s Who',
    'Wire',
    'Wyper',
    'X Drake',
    'Yama',
    'Yamakaji',
    'Yamato',
    'Yasakani Sacred Jewel',
    'Yasopp',
    'Yokozuna',
    'York',
    'Yosaku & Johnny',
    'You Can Be My Samurai!!',
    'You May Be a Fool...but I Still Love You',
    'Zambai',
    'Zeff',
    'Zeo',
    'Zeus',
    'Zephyr',
    'Zephyr(Navy)',
    'Zoro-Juurou',
];
