export const sourcesOptions = [
  '1st Anniversary Chinese (CH)',
  '1st Anniversary English',
  '1st Anniversary Japanese',
  '2nd Anniversary Japanese',
  'AA - OP01',
  'AA - OP02',
  'AA - OP03',
  'AA - OP04',
  'AA - OP05',
  'AA - OP06',
  'AA - OP07',
  'AA - OP08',
  'AA - OP09',
  'AA - OP10',
  'AA - OP11',
  'AA - OP12',
  'AA - PRB01',
  'AA - ST10',
  'AA - ST15',
  'AA - ST19',
  'AA - ST20',
  'Box Topper - OP01',
  'Box Topper - OP02',
  'Celebration Pack - Championship 2023',
  'Celebration Pack - Championship 2024',
  'Celebration Pack - Championship 2025',
  'Chinese promo (CH)',
  'Dash Pack - OP04',
  'Let\'s get started campaign (JP)',
  'Event Pack - Championship 2023',
  'Event Pack Vol. 2',
  'Flagship (JP)',
  'Full Art - PRB01',
  'Gift Pack Vol. 1',
  'Premium Card Collection - 25th years anniversary',
  'Premium Card Collection - 6 Assort Vol.1',
  'Premium Card Collection - Best Selection Vol. 1',
  'Premium Card Collection - Best Selection Vol. 2',
  'Premium Card Collection - Best Selection Vol. 3',
  'Premium Card Collection - Best Selection Vol. 5',
  'Premium Card Collection - Film Red',
  'Premium Card Collection - Girls Collection',
  'Premium Card Collection - Uta',
  'Promotional Pack 2023',
  'Promotion Pack EX Vol.1 (JP)',
  'Regional Pack 2023 Vol. 1',
  'Regional Pack 2023 Vol. 2',
  'Regional Pack 2024 Vol. 1',
  'Regional Pack 2024 Vol. 3',
  'Sealed Battle Vol. 1',
  'SP - OP03',
  'SP - OP04',
  'SP - OP05',
  'SP - OP06',
  'SP - OP07',
  'SP - OP08',
  'SP - OP09',
  'SP - OP10',
  'SP - OP11',
  'SP - OP12',
  'Special Foil - PRB01',
  'Special Goods Set - Former Four Emperors',
  'Special Goods Set - Ace/Sabo/Luffy',
  'Store Championship Vol. 1',
  'Store Championship Vol. 2',
  'Tournament Pack Vol. 2',
  'Tournament Pack Vol. 4',
  'Tournament Pack Vol. 6',
  'Tournament Pack Vol. 7',
  'Tournament Pack Vol. 8',
  'Tournament Pack Vol. 10',
  'Treasure Rare - OP07 (CH)',
  'Treasure Rare - OP08 (CH)',
  'Treasure Rare - OP09 (CH)',
];
