export const sourcesOptions = [
  '',
  '1st Anniversary Chinese (CH)',
  '1st Anniversary English',
  '1st Anniversary Japanese',
  '2nd Anniversary Japanese',
  '2nd Anniversary English',
  '2nd Anniversary Chinese (CH)',
  '3rd Anniversary Chinese (CH)',
  'AA - OP01',
  'AA - OP02',
  'AA - OP03',
  'AA - OP04',
  'AA - OP05',
  'AA - OP06',
  'AA - OP07',
  'AA - OP08',
  'AA - OP09',
  'AA - OP10',
  'AA - OP11',
  'AA - OP12',
  'AA - OP13',
  'AA - EB01',
  'AA - EB02',
  'AA - PRB01',
  'AA - PRB02',
  'AA - ST10',
  'AA - ST15',
  'AA - ST18',
  'AA - ST19',
  'AA - ST20',
  'AA - ST23',
  'AA - ST24',
  'AA - ST25',
  'AA - ST26',
  'AA - ST27',
  'AA - ST28',
  'Bandai Cards Fest 2025',
  'Beginners Deck Party ST-15 - ST-20 (FR)',
  'Beginners Deck Party ST-23 - ST-28',
  'Box Topper - OP01',
  'Box Topper - OP02',
  'Celebration Pack - Championship 2023',
  'Celebration Pack - Championship 2024',
  'Celebration Pack - Championship 2025',
  'Chinese promo (CH)',
  'Chinese New Year Promo Vol. 2 (CH)',
  'Dash Pack - OP04',
  'Dash Pack - OP10',
  'LA Dodgers Promo',
  'Let\'s get started campaign (JP)',
  'Event Pack - Championship 2023',
  'Event Pack Vol. 2',
  'Event Pack Vol. 3',
  'Event Pack Vol. 5',
  'Flagship (JP)',
  'Full Art - PRB01',
  'Gift Pack Vol. 1',
  'Illustration Box EX',
  'Judge pack Vol. 1 (JP)',
  'Judge pack Vol. 2 (JP)',
  'Jump Promo',
  'New Year Event - 2025',
  'Official Playmat Limited Edition Vol.3',
  'One Piece Day - 2024',
  'One Piece Day - 2024 (EN)',
  'Pre Release - OP03',
  'Premium Card Collection - 25th years anniversary',
  'Premium Card Collection - 6 Assort Vol.1',
  'Premium Card Collection - Best Selection Vol. 1',
  'Premium Card Collection - Best Selection Vol. 2',
  'Premium Card Collection - Best Selection Vol. 3',
  'Premium Card Collection - Best Selection Vol. 4',
  'Premium Card Collection - Best Selection Vol. 5',
  'Premium Card Collection - Film Red',
  'Premium Card Collection - Girls Collection',
  'Premium Card Collection - Uta',
  'Premium Card Collection - Seven Warlords of the Sea',
  'Promotional Pack 2023',
  'Promotion Pack EX Vol.1 (JP)',
  'Promotion Pack EX Vol.2 (JP)',
  'Promotion Pack Vol. 7 (JP)',
  'PSA Promo',
  'Regional Pack 2023 Vol. 1',
  'Regional Pack 2023 Vol. 2',
  'Regional Pack 2024 Vol. 1',
  'Regional Pack 2024 Vol. 2',
  'Regional Pack 2024 Vol. 3',
  'Regional Pack 2025 Vol. 1',
  'Regional Pack 2025 Vol. 2',
  'Sealed Battle Vol. 1',
  'Sound Loader Vol. 1',
  'Sound Loader Vol. 2',
  'Sound Loader Vol. 3',
  'SP - OP03',
  'SP - OP04',
  'SP - OP05',
  'SP - OP06',
  'SP - OP07',
  'SP - OP08',
  'SP - OP09',
  'SP - OP10',
  'SP - OP11',
  'SP - OP12',
  'SP - OP13',
  'SP - PRB02',
  'Special Foil - PRB01',
  'Special Foil - PRB02',
  'Special Goods Set - Former Four Emperors',
  'Special Goods Set - Ace/Sabo/Luffy',
  'Store Championship Vol. 1',
  'Store Championship Vol. 2',
  'Store Treasure Cup Vol. 1',
  'Store Treasure Cup Vol. 2',
  'Super Pre Release',
  'Textured Foil - PRB01',
  'Tournament Pack Vol. 2',
  'Tournament Pack Vol. 3',
  'Tournament Pack Vol. 4',
  'Tournament Pack Vol. 5',
  'Tournament Pack Vol. 6',
  'Tournament Pack Vol. 7',
  'Tournament Pack Vol. 8',
  'Tournament Pack Vol. 9',
  'Tournament Pack Vol. 10',
  'Tournament Pack Vol. 11',
  'Tournament Pack Vol. 12',
  'Treasure Booster Vol. 1',
  'Treasure Campaign Pack - 3rd Anniversary',
  'Treasure Rare - OP06 (EN)',
  'Treasure Rare - OP07 (CH)',
  'Treasure Rare - OP08 (EN)',
  'Treasure Rare - OP08 (CH)',
  'Treasure Rare - OP09 (CH)',
  'Treasure Rare - OP10 (CH)',
  'Treasure Rare - OP10 (EN)',
  'Treasure Rare - OP10 (FR)',
  'Treasure Rare - OP09 (FR)',
  'Treasure Rare - OP11 (CH)',
  'Treasure Rare - OP11 (EN)',
  'Treasure Rare - OP11 (FR)',
  'Treasure Rare - OP12 (CH)',
  'Treasure Rare - OP12 (EN)',
  'Treasure Rare - OP12 (FR)',
  'Welcome Pack Vol. 1',
];
