export const typesOptions = [
  '',
  'Alabasta',
  'Animal',
  'Animal Kingdom Pirates',
  'Arlong Pirates',
  'Baroque Works',
  'Barto Club',
  'Beautiful Pirates',
  'Biological Weapon',
  'Big Mom Pirates',
  'Black Cat Pirates',
  'Blackbeard Pirates',
  'Bonney Pirates',
  'Buggy Pirates',
  'Caribou Pirates',
  'CP0',
  'CP6',
  'CP7',
  'CP9',
  'Cross Guild',
  'Donquixote Pirates',
  'Drake Pirates',
  'Dressrosa',
  'East Blue',
  'Egghead',
  'FILM',
  'Fish-Man',
  'Fish-Man Island',
  'Flevance',
  'Former Baroque Works',
  'Former Navy',
  'Former Whitebeard Pirates',
  'Franky Family',
  'Galley-la Company',
  'GERMA 66',
  'Giant',
  'Golden Lion Pirates',
  'Happosui Army',
  'Hawkins Pirates',
  'Heart Pirates',
  'Homies',
  'Impel Down',
  'Jailer Beast',
  'Jaya',
  'Kid Pirates',
  'Kingdom of GERMA',
  'Kouzuki Clan',
  'Krieg Pirates',
  'Kuja Pirates',
  'Land of Wano',
  'Merfolk',
  'Minks',
  'Mountain Bandits',
  'Navy',
  'Neo Navy',
  'New Giant Warrior Pirates',
  'ODYSSEY',
  'Ohara',
  'On-Air Pirates',
  'Plague',
  'Punk Hazard',
  'Red-Haired Pirates',
  'Revolutionary Army',
  'Scientist',
  'Shandian Warrior',
  'Sky Island',
  'SMILE',
  'Sniper Island',
  'Spade Pirates',
  'Straw Hat Crew',
  'Supernovas',
  'The Akazaya Nine',
  'The Four Emperrors',
  'The Pirates Fest',
  'The Seven Warlords of the Sea',
  'The Vinsmoke Family',
  'Thriller Bark Pirates',
  'Water Seven',
  'Whitebeard Pirates',
  'Whitebeard Pirates Allies',
  'Whole Cake Island',
  'Windmill Village',
  'World Government	',
  'World Pirates',
];
