export const typesOptions = [
  '',
  'Accino Family',
  'Alabasta',
  'Amazon Lily',
  'Animal',
  'Animal Kingdom Pirates',
  'Arlong Pirates',
  'Asuka Island',
  'Baroque Works',
  'Barto Club',
  'Baterilla',
  'Beautiful Pirates',
  'Biological Weapon',
  'Big Mom Pirates',
  'Black Cat Pirates',
  'Blackbeard Pirates',
  'Bluejam Pirates',
  'Bonney Pirates',
  'Botanist',
  'Bowin Island',
  'Buggy\'s Delivery',
  'Buggy Pirates',
  'Caribou Pirates',
  'Celestial Dragons',
  'CP0',
  'CP6',
  'CP7',
  'CP9',
  'Cross Guild',
  'Crown Island',
  'Donquixote Pirates',
  'Drake Pirates',
  'Dressrosa',
  'Drum Kingdom',
  'East Blue',
  'Egghead',
  'Eldoraggo Crew',
  'Fake Straw Hat Crew',
  'Fallen Monk Pirates',
  'FILM',
  'Firetank Pirates',
  'Fish-Man',
  'Fish-Man Island',
  'Five Elders',
  'Flevance',
  'Flying Pirates',
  'Foolshout Island',
  'Former Arlong Pirates',
  'Former Baroque Works',
  'Former CP9',
  'Former Navy',
  'Former Rocks Pirates',
  'Former Roger Pirates',
  'Former Rumbar Pirates',
  'Former Whitebeard Pirates',
  'Foxy Pirates',
  'Galley-la Company',
  'Gasparde Pirates',
  'GERMA 66',
  'Giant',
  'Goa Kingdom',
  'Golden Lion Pirates',
  'Grantesoro',
  'Gyro Pirates',
  'Happosui Army',
  'Hawkins Pirates',
  'Heart Pirates',
  'Homies',
  'Impel Down',
  'Jailer Beast',
  'Jaya',
  'Journalist',
  'Kid Pirates',
  'King of the Pirates',
  'Kingdom of GERMA',
  'Kouzuki Clan',
  'Krieg Pirates',
  'Kuja Pirates',
  'Kurozumi Clan',
  'Land of Wano',
  'Long Ring Long Land',
  'Lulusia Kingdom',
  'Lunarian',
  'Mary Geoise',
  'Mecha Island',
  'Merfolk',
  'Minks',
  'Momonga',
  'Moon',
  'Mountain Bandits',
  'Muggy Kingdom',
  'Mugiwara Chase',
  'Music',
  'Navy',
  'Neo Navy',
  'New Fish-man Pirates',
  'New Giant Pirates',
  'ODYSSEY',
  'Ohara',
  'Omatsuri Island',
  'On-Air Pirates',
  'Plague',
  'Punk Hazard',
  'Red-Haired Pirates',
  'Revolutionary Army',
  'Roger Pirates',
  'Saruyama Alliance',
  'Scientist',
  'Seraphim',
  'Shandian Warrior',
  'Shimotsuki Village',
  'Shipbuilding Town',
  'Sky Island',
  'SMILE',
  'Sniper Island',
  'Spade Pirates',
  'Straw Hat Crew',
  'The Sun Pirates',
  'Supernovas',
  'SWORD',
  'The Akazaya Nine',
  'The Flying Fish Riders',
  'The Four Emperors',
  'The Franky Family',
  'The Pirates Fest',
  'The Seven Warlords of the Sea',
  'The Vinsmoke Family',
  'Thriller Bark Pirates',
  'The Tontattas',
  'Trump Pirates',
  'Vassals',
  'Vinsmoke Family',
  'Water Seven',
  'Weevil\'s Mother',
  'Whitebeard Pirates',
  'Whitebeard Pirates Allies',
  'Whole Cake Island',
  'Windmill Village',
  'World Government',
  'World Pirates',
  '?',
  'Neptunian'
];
